spring.application.name=patient-service

# --- Database Configuration ---
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=patient_admin
spring.datasource.password=patient123

# --- Hibernate Settings ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

server.port=4000